# Generated by Django 5.0.6 on 2024-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=255)),
                ('recipient_phone_number', models.CharField(max_length=13)),
                ('recipient_full_name', models.CharField(max_length=255)),
                ('sender_email', models.CharField(max_length=255)),
                ('sender_phone_number', models.CharField(max_length=13)),
                ('sender_full_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')])),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')])),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=455)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
