# Generated by Django 5.0.6 on 2024-06-13 08:52

import apps.general.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(blank=True, default=False, null=True)),
                ('from_user_email', models.CharField(max_length=255)),
                ('from_user_phone_number', models.CharField(max_length=13, unique=True, validators=[apps.general.validate.phone_number_validate])),
                ('from_user_full_name', models.CharField(max_length=255)),
                ('to_user_email', models.CharField(max_length=255)),
                ('to_user_phone_number', models.CharField(max_length=13, unique=True, validators=[apps.general.validate.phone_number_validate])),
                ('to_user_full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')])),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(0, 'exam result'), (1, 'on attendance'), (2, 'payment time'), (3, 'Warning')])),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=455)),
            ],
        ),
    ]
