# Generated by Django 5.0.6 on 2024-06-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
