# Generated by Django 5.0.6 on 2024-06-13 08:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('because_of', 'Because Of'), ('without_reason', 'Without Reason'), ('came', 'Came')], max_length=30)),
                ('attendance_date', models.DateField()),
                ('reason', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
    ]
